# Generated by Django 2.2.13 on 2020-06-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_projector_default_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='projector',
            name='show_stimmung',
            field=models.BooleanField(default=True),
        ),
    ]
