# Generated by Django 2.2.13 on 2020-06-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_projector_show_stimmung'),
        ('core', '0033_live_stream_permission'),
    ]

    operations = [
    ]
