# Generated by Django 2.2.13 on 2020-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_monospace_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='projector',
            name='show_stimmung',
            field=models.BooleanField(default=True),
        ),
    ]
