# Generated by Django 2.2.16 on 2020-10-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_merge_20200830_1217'),
        ('core', '0035_autopilot_permission'),
    ]

    operations = [
    ]
